import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./ui/globals.css";
import { Navbar } from "./ui/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen flex flex-col bg-gradient-to-br from-pink-400 to-blue-500`}>
        <Navbar/>
        <main className="flex flex-1">
          {children}
        </main>
        
      </body>
    </html>
  );
}
